FROM golang:1.22-alpine
EXPOSE 80 4000
WORKDIR /app
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest
COPY go.mod go.sum ./
RUN go mod tidy


COPY . .

#ENV GO111MODULE=off
RUN cd cmd ; CGO_ENABLED=0 go build -gcflags "all=-N -l" -o app

CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/cmd/app" ]