package database_data

import (
	"goshipbuilder/models"
)

func GetUpgradeSupplies() []*models.UpgradeSupplies {
	upgradeSuppliesData := []*models.UpgradeSupplies{
		{
			Name:        "Heavy Weaponry",
			BoardChance: f(15),
			CrewBreach:  f(15),
			CrewDamage:  f(30),
		},
		{
			Name:        "Medium Weaponry",
			BoardChance: f(20),
			CrewBreach:  f(20),
			CrewDamage:  f(25),
		},
		{
			Name:        "Light Weaponry",
			BoardChance: f(25),
			CrewBreach:  f(25),
			CrewDamage:  f(20),
		},
		{
			Name:       "Practice Targets",
			Lesser:     f(10),
			CrewBreach: f(30),
		},
		{
			Name:      "Silk Hammocks",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(2.5),
			HealBonus: f(20),
		},
		{
			Name:      "Fur Bedrolls",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			HealBonus: f(30),
		},
		{
			Name:        "Boarding Knives",
			BoardChance: f(150),
			CrewBreach:  f(15),
			CrewDamage:  f(10),
		},
		{
			Name:        "Stockade",
			Speed:       f(2.5),
			BoardChance: f(50),
			CrewDamage:  f(15),
		},
		{
			Name:      "Bananas",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(2.5),
			CrewHits:  f(10),
			HealBonus: f(10),
		},
		{
			Name:      "Limes",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(2.5),
			CrewHits:  f(15),
			HealBonus: f(5),
		},
		{
			Name:      "Delicious Rations",
			Speed:     f(2.5),
			CrewHits:  f(20),
			HealBonus: f(15),
		},
		{
			Name:      "Savory Rations",
			Speed:     f(2.5),
			CrewHits:  f(25),
			HealBonus: f(10),
		},
		{
			Name:      "Healthy Rations",
			Speed:     f(2.5),
			CrewHits:  f(30),
			HealBonus: f(5),
		},
		{
			Name:      "Wild Game",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(2.5),
			CrewHits:  f(15),
			HealBonus: f(5),
			Fishing:   f(5),
			Spy:       f(10),
		},
		{
			Name:        "Hardtack",
			Speed:       f(1),
			Lesser:      f(5),
			Regular:     f(5),
			Greater:     f(5),
			BoardChance: f(50),
			CrewHits:    f(15),
			CrewBreach:  f(5),
			CrewDamage:  f(5),
			HealBonus:   f(5),
		},
		{
			Name:      "Hookah",
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(10),
			HealBonus: f(20),
			Fishing:   f(5),
		},
		{
			Name:      "Medical Supplies",
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(2.5),
			CrewHits:  f(10),
			HealBonus: f(15),
		},
		{
			Name:      "Alchemical Supplies",
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(5),
			CrewHits:  f(5),
			HealBonus: f(10),
		},
		{
			Name:      "Spices",
			Speed:     f(1),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
			Doubloons: f(7.5),
		},
		{
			Name:        "Ale Supply",
			Speed:       f(1),
			Lesser:      f(5),
			Regular:     f(5),
			Greater:     f(5),
			BoardChance: f(25),
			CrewBreach:  f(10),
			CrewDamage:  f(10),
			HealBonus:   f(5),
			Fishing:     f(5),
		},
		{
			Name:        "Smoke Bombs",
			Lesser:      f(5),
			Regular:     f(10),
			Greater:     f(5),
			BoardChance: f(25),
			Wake:        f(20),
		},
		{
			Name:  "Intercepted Orders",
			Speed: f(2.5),
			Spy:   f(10),
			Wake:  f(10),
		},
		{
			Name:      "Crew Hatches",
			Speed:     f(1),
			Lesser:    f(10),
			Regular:   f(10),
			Greater:   f(5),
			HealBonus: f(0),
			Wake:      f(10),
		},
		{
			Name:        "Dueling Rapiers",
			BoardChance: f(50),
			CrewBreach:  f(30),
			CrewDamage:  f(15),
		},
	}
	return upgradeSuppliesData
}
