package database_data

import "goshipbuilder/models"

func GetUpgradeSpecialty() []*models.UpgradeSpecialty {
	upgradeSpecialty := []*models.UpgradeSpecialty{
		{
			Name:  "Custom Rigging",
			Sails: f(20),
			Speed: f(5),
		},
		{
			Name:  "Exceptional Oars",
			Speed: f(7.5),
		},
		{
			Name:      "Storage Lockers",
			HoldCap:   f(400),
			Doubloons: f(5),
		},
		{
			Name:      "Cannon Targets",
			CannonAcc: f(7.5),
			CannonDmg: f(2.5),
			RldSpeed:  f(20),
		},
		{
			Name:     "Routine Maintenance",
			Hull:     f(5),
			Sails:    f(10),
			Guns:     f(10),
			Speed:    f(1),
			RepairCd: f(10),
			HullRp:   f(25),
			SailRp:   f(25),
			GunsRp:   f(25),
		},
		{
			Name:        "Fearsome Totem",
			Speed:       f(1),
			Greater:     f(10),
			BoardChance: f(100),
			CrewDamage:  f(20),
		},
		{
			Name:        "Tavern Connections",
			BoardChance: f(75),
			CrewHits:    f(20),
			CrewBreach:  f(15),
			CrewDamage:  f(7.5),
			HealBonus:   f(10),
			Fishing:     f(5),
			Spy:         f(10),
		},
		{
			Name:     "Carpentry Station",
			Hull:     f(10),
			RepairCd: f(15),
			HullRp:   f(50),
			SailRp:   f(25),
			GunsRp:   f(25),
		},
		{
			Name:     "Sewing Station",
			Sails:    f(20),
			Speed:    f(1),
			RepairCd: f(15),
			HullRp:   f(25),
			SailRp:   f(50),
			GunsRp:   f(25),
		},
		{
			Name:     "Gunsmithing Station",
			Guns:     f(20),
			RepairCd: f(15),
			HullRp:   f(25),
			SailRp:   f(25),
			GunsRp:   f(50),
		},
		{
			Name:      "Galley Station",
			Speed:     f(2.5),
			CrewHits:  f(25),
			HealBonus: f(15),
			Fishing:   f(5),
		},
		{
			Name:    "Mongbat Figurehead",
			Lesser:  f(20),
			Regular: f(10),
			Greater: f(10),
		},
		{
			Name:    "Eagle Figurehead",
			Lesser:  f(10),
			Regular: f(20),
			Greater: f(10),
		},
		{
			Name:    "Gorgon Figurehead",
			Lesser:  f(10),
			Regular: f(10),
			Greater: f(20),
		},
		{
			Name:      "Exceptional Powder",
			CannonAcc: f(2.5),
			CannonDmg: f(10),
			Regular:   f(10),
		},
		{
			Name:      "Stacked Powderkegs",
			CannonDmg: f(5),
			RldSpeed:  f(40),
			HoldCap:   f(100),
			Lesser:    f(10),
		},
		{
			Name:      "Smoothbore Cannonshot",
			CannonAcc: f(5),
			CannonDmg: f(5),
			Regular:   f(10),
		},
		{
			Name:      "Auxiliary Cannons",
			CannonDmg: f(7.5),
			Lesser:    f(10),
		},
		{
			Name:     "Exotic Bait",
			CrewHits: f(10),
			Fishing:  f(10),
			Spy:      f(10),
		},
		{
			Name:     "Pristine Lumber",
			Hull:     f(20),
			HoldCap:  f(50),
			RepairCd: f(5),
			HullRp:   f(25),
		},
		{
			Name:     "Exquisite Cloth",
			Sails:    f(40),
			Speed:    f(2.5),
			RepairCd: f(5),
			SailRp:   f(25),
		},
		{
			Name:      "Flawless Iron",
			Guns:      f(40),
			CannonAcc: f(2.5),
			RepairCd:  f(5),
			GunsRp:    f(25),
		},
		{
			Name:      "Powder Carts",
			CannonDmg: f(5),
			RldSpeed:  f(60),
			HoldCap:   f(50),
			Lesser:    f(5),
			Regular:   f(5),
			Greater:   f(5),
		},
		{
			Name:      "Accurate Maps",
			Speed:     f(5),
			Doubloons: f(2.5),
		},
		{
			Name:    "Navigation Chart",
			Speed:   f(5),
			Greater: f(5),
			Wake:    f(10),
		},
		{
			Name:  "Exquisite Globe",
			Speed: f(5),
			Wake:  f(20),
		},
		{
			Name:      "Shipping Contracts",
			Doubloons: f(15),
		},
		{
			Name:      "Luxury Goods",
			Doubloons: f(12.5),
			CrewHits:  f(5),
			HealBonus: f(5),
		},
		{
			Name:      "Livestock",
			Doubloons: f(10),
			CrewHits:  f(10),
			HealBonus: f(10),
		},
		{
			Name:      "Grain Shipment",
			Doubloons: f(10),
			CrewHits:  f(15),
			HealBonus: f(5),
		},
		{
			Name:      "Crows Nest",
			CannonAcc: f(2.5),
			Regular:   f(10),
			Spy:       f(40),
		},
		{
			Name:  "Weathervane",
			Speed: f(5),
			Spy:   f(10),
			Wake:  f(10),
		},
		{
			Name:  "Telescope",
			Speed: f(2.5),
			Spy:   f(20),
			Wake:  f(20),
		},
		{
			Name:    "Signal Pigeons",
			Lesser:  f(10),
			Regular: f(10),
			Greater: f(10),
			Wake:    f(20),
		},
		{
			Name:      "Blast Furnace",
			CannonDmg: f(5),
			Regular:   f(10),
			RepairCd:  f(25),
		},
	}
	return upgradeSpecialty
}
